### ISSUE TITLE
port single index approach to search_lucene

### ISSUE THREAD

**Issue by butonic** [owncloud/search_elastic#12]
@PVince81 @VicDeo the search elastic app uses a single index and [stores the users that have access to a document in the index](https://github.com/owncloud/search_elastic/blob/master/lib/client.php#L220). This allows [passing the user to the search query](https://github.com/owncloud/search_elastic/blob/master/search/elasticsearchprovider.php#L47). It also requires to [update the search index on share events](https://github.com/owncloud/search_elastic/blob/master/hooks/files.php#L174)

Storing the users that have access to a file in the index is the recommended way to combine search with permissions. A conclusion that was shaped in discussinos with lucene developers at fosdem.

**Comment by micbar** [comment]
outdated
