### ISSUE TITLE
Full Text Search 1.0 cannot connect to elasticsearch 7.0

### ISSUE THREAD

**Issue by zubanst** [owncloud/search_elastic#197]
"name" : "node-1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "HccrHHC1RNuo8Jkvu5WTrQ",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"

At Index setup the message is: Index not set up

**Comment by micbar** [comment]
fixed with #215
