### ISSUE TITLE
Support Elastic Search 6.x or 7.x

### ISSUE THREAD

**Issue by hodyroff** [owncloud/search_elastic#21]
https://www.elastic.co/support/eol
With release of 6.0 - 2.4.x will be obsolete.
Sounds best to go to 6.0 right away at this time and even do Beta earlier.

Tasks:
- [x] check how files attachment works in elastic 5/6
  -> renamed to ingest-attachment and has different syntax
- [x] check if we can update/change the usage of status table
  -> idea: remove the status table; use oc_properties; queue files that require indexing (seperate table)
 ->

- [x] change table/indexes to the new supported formats
- [x] upgrade dependencies/vendor files 
- [ ] support authorization methods ([X-PACK(https://www.elastic.co/guide/en/x-pack/current/xpack-security.html))

**Comment by BlackQube** [comment]
Are there any updates on this topic?

**Comment by hodyroff** [comment]
Honestly no, we could fulfill each customer requirements with the 5.6 version till now ...
We do restrict access to such servers to only respond to the ownCloud Server of course.
In the meantime we would target 7.x  ...
Anything which is clearly better in newer versions? Any challenges with deploying 5.6 and securing it that way?

**Comment by DeepDiver1975** [comment]
Current plan:
- keep search_elastic 1.x.x compatible with ES6 (technically ES5 as well - but it is EOL anyway)
- build search_elastic 2.x.x fpr ES7

This will result in a branch 1.x for the 1.0.0 series. master branch will be for the ES7 development

@hodyroff @micbar FYI

**Comment by micbar** [comment]
good plan! keep 1.x branch only for hotfixes.

2.x branch for further development.

**Comment by DeepDiver1975** [comment]
> 2.x branch for further development.

any a 3.x branch for ES8  one day ....

**Comment by micbar** [comment]
closed by #215
