### ISSUE TITLE
Release search_elastic 2.0.0

### ISSUE THREAD

**Issue by xoxys** [owncloud/search_elastic#220]
### Reason

- Add ES7 compatibility
- https://github.com/owncloud/search_elastic/issues/197
- https://github.com/owncloud/search_elastic/issues/194

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> #221
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [ ] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [x] https://github.com/owncloud/docs/issues/3929

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [ ] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [x] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by phil-davis** [comment]
"Add ES7 compatibility"
In PR #215 we changed the acceptance tests to run with ES7, and no longer run CI with ES5.

Are we still supporting ES5?
What is ES6? Do we support that at all?

Maybe this release is supporting ES7 and dropping support for all other ES* versions before 7?

It would be good to state what the support matrix is, and we can make sure to test that.

**Comment by xoxys** [comment]
Good point, maybe we need a major version bump. IMO ES5 should be dropped, not sure about ES6...

**Comment by jnweiger** [comment]
Signed RC1 first, then prio after openidconnect.

**Comment by jnweiger** [comment]
RC1 done at version 1.1.0 for now: https://github.com/owncloud/search_elastic/releases/tag/v1.1.0-rc1

@xoxys if we break ES6 support, we should definitly jump to 2.0.0  -- if we just no longer test it and call it deprecrcated, then semver asks for a minor version bump.

**Comment by phil-davis** [comment]
"if we break ES6 support" - IMO we have not supported ES6 at all so far. And this release skips it. But in any case, if we are officially dropping ES5 and adding ES7 then it sounds like a major version 2.0.0 would be good.

**Comment by jnweiger** [comment]
Okay, can somebody merge https://github.com/owncloud/search_elastic/pull/215 please, then I'll build an 2.0.0-rc1 release candidate.

**Comment by xoxys** [comment]
@phil-davis The PR is ready to merge and as we agreed to drop/deprecate the support for older ES version we don't need to adjust the tests, right?

**Comment by phil-davis** [comment]
> The PR is ready to merge and as we agreed to drop/deprecate the support for older ES version we don't need to adjust the tests, right?

I "someone" has agreed that support for ES5 is to be dropped, then we merge the PR, change the version to 2.0.0, set owncloud min-version to whatever we think we will support with search_elastic 2.0.0 and get on with the release.

Who is "someone" that makes this decision?

**Comment by pmaier1** [comment]
Yes, ES5 support can be dropped with this release. Needs doc update @mmattel.

**Comment by jnweiger** [comment]
ready for testing: https://github.com/owncloud/search_elastic/releases/tag/v2.0.0-rc1

**Comment by micbar** [comment]
@jnweiger If this takes longer, could we include #212 ?

**Comment by phil-davis** [comment]
Note: ownCloud 10 core master has dropped support for PHP 7.2. That will happen for core 10.9.0 release.

PR #231 modifies this app to do the same - adjust CI to not use PHP 7.2 any more, and set PHP to 7.3 in `composer.json`.

I have not merged that yet. If I merge the PR, then that might prevent the next search_elastic release from working with a combination of ownCloud core 10.8.0 and PHP 7.2.

Are there sites that would still want the option to run core 10.8.0, search_elastic 2.0.0 and PHP 7.2?

**Comment by xoxys** [comment]
No issue from our side.

**Comment by mmattel** [comment]
> Needs doc update @mmattel

After checking the documentation, there is no need for a change in docs - as long there are no changes in the app regarding behaviour or commands. Docs only has occ comands for ES which do not mention any ES version used and no own ES page (maybe an idea to add one...?).

**Comment by pmaier1** [comment]
I've summarized the doc needs here https://github.com/owncloud/docs/issues/3996

**Comment by micbar** [comment]
#212 was merged.

It has more implications to the docs as planned. needs an update. Information is here https://github.com/owncloud/search_elastic/pull/212#issuecomment-983361975

**Comment by micbar** [comment]
@jnweiger @JammingBen This is planned to be tested on cloud.owncloud.com for performance.

**Comment by pmaier1** [comment]
@xoxys might want to check the RC then.

**Comment by xoxys** [comment]
No I dont want to mess around with manual RC installations. Still waiting for the release.

**Comment by jnweiger** [comment]
Ready for testing: https://github.com/owncloud/search_elastic/releases/tag/v2.0.0-rc2

This includes #212

**Comment by GeraldLeikam** [comment]
Close after release
