### ISSUE TITLE
Investigate phan-suppress-next-line

### ISSUE THREAD

**Issue by phil-davis** [owncloud/search_elastic#232]
There are quite a lot of places in the code that have `phan-suppress-next-line` comments that suppress messages from `phan` code analysis.

Search for these and investigate each one. See if the code can be adjusted to make `phan` happy.

**Comment by phil-davis** [comment]
QA Automation team - please have a look at these and adjust any that are "easy/obvious" to fix. And comment in this issue about code that needs more than easy/obvious changes. Then devs can look at whatever remains.

**Comment by kiranparajuli589** [comment]
occurrences in the code_base:
- **PhanDeprecatedFunction**: https://github.com/owncloud/search_elastic/blob/master/lib/Jobs/SearchJobList.php?plain=1#L101-L104
- **PhanPossiblyInfiniteRecursionSameParams**: https://github.com/owncloud/search_elastic/blob/master/lib/Jobs/SearchJobList.php?plain=1#L112-L123
- **PhanRedefinedInheritedInterface**: https://github.com/owncloud/search_elastic/blob/master/lib/ElasticLogger.php?plain=1#L8
- **PhanUndeclaredClassReference**:
  - https://github.com/owncloud/search_elastic/blob/master/lib/Db/StatusMapper.php?plain=1#L263-L269
  - https://github.com/owncloud/search_elastic/blob/master/lib/Jobs/UpdateContent.php?plain=1#L140-L141
- **PhanUndeclaredMethod**: https://github.com/owncloud/search_elastic/blob/master/lib/SearchElasticService.php?plain=1#L305-L306
- **PhanTypeNoAccessiblePropertiesForeach**: https://github.com/owncloud/search_elastic/blob/master/lib/SearchElasticService.php?plain=1#L392-L397
- **PhanTypeArraySuspicious**: https://github.com/owncloud/search_elastic/blob/master/lib/SearchElasticService.php?plain=1#L530-L530
