### ISSUE TITLE
[QA] upgrade from 2.0.0 to 2.1.0 disconnects the elastic host

### ISSUE THREAD

**Issue by jnweiger** [owncloud/search_elastic#255]
Seen with 2.1.0 on owncloud 10.9.1

* configure 2.0.0 in the admin settings search. There is only one text field, input the elastic server address there '172.17.0.3:9200`
* the connection icon turns from red to green.
* `occ search:index:update` indexes all my 9 files.
![image](https://user-images.githubusercontent.com/1108546/154733855-cba1c92d-d0de-4e7b-8768-51e14afe3b28.png)

* upgrade the app to version 2.1.0
* run `occ upgrade`
* the search engine becomes defunct. The search host in the admin UI is replaced with the string `on`
![image](https://user-images.githubusercontent.com/1108546/154734230-f04a9908-447b-4ff5-a723-1137cb643ccc.png)

Expected behaviour:
* the config is preserved.
* having no username and password is accepted, as it was acceptable before.

Workaround:
* re-enter host:port
* enter random username and password.

**Comment by hodyroff** [comment]
Yes, the olf config must be preserverd.
It must still be possible to work unauthenticated.

**Comment by pmaier1** [comment]
Blocker for the search_elastic 2.1.0 release.
@ahherrera can you check, please?

**Comment by jnweiger** [comment]
Alberto cannot reproduce. And I cannot reproduce either.
We both can upgrade just fine now... hmm.
