### ISSUE TITLE
Release search_elastic 2.4.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/search_elastic#323]
### Reasons

- Needed to go with server core 10.13 because of the Symfony 4 to 5 upgrade https://github.com/owncloud/core/issues/39630
- PR #322 made code changes needed for Symfony 5
- https://github.com/owncloud/search_elastic/pull/319 
  - https://github.com/owncloud/enterprise/issues/5556
  - https://github.com/owncloud/enterprise/issues/5643
  
Note: the change in that PR also works fine with server core 10.12 and before, so there should be no need to bump the core min-version.

The app can be released any time before 10.13 - it should work fine with any of the recent oC10 core releases.

## Full testplan needed
- [x] https://github.com/owncloud/search_elastic/issues/328

### Product approval 

- [x] Verify transifex commits (enterprise should update weekly, others daily): If folder `l10n` exists, then `git log` should show '[tx] updated from transifex` ...
- [x] Ping ProductManagement to check `info.xml` description and screenshot

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core))
- [x] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in https://github.com/owncloud/docs-server/issues/new .

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch (`git pull; git checkout -b release-x.x.x`) from here:
- [x] Bump version in `appinfo/info.xml` (no version suffix)
- [x] Check php version dependency and minimum ownCloud version dependency in `appinfo/info.xml`
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] `git tag -s v${version}-rc.1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc.1` (see handbook for how to build)
- [x] Check buildlog for security reports
- [x] Check github security tab dependabot reports
    - [ ] -> if critical or high entries are reported: open a release blocker issue.
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [ ] Watch out for untranslated strings when locale is de oder de_DE.
    - [ ] PHP 7.3 compatibility (`HCLOUD_SERVER_IMAGE=debian-10 OC10_VERSION=10.11 oc10.sh ...`)
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by jnweiger** [comment]
Issues seen while testing
* [ ] https://github.com/owncloud/search_elastic/issues/329

**Comment by jnweiger** [comment]
We have RC1:
- https://github.com/owncloud/search_elastic/releases/download/v2.4.0-rc.1/search_elastic-2.4.0-rc.1.tar.gz

**Comment by jnweiger** [comment]
Changelog QA passed. the critical tokenizer error #331 is fixed. Some more errors around  #287 exist, new issues opened. Not considered blockers.

**Comment by phil-davis** [comment]
https://github.com/owncloud/search_elastic/releases/tag/v2.4.0
was released 2 Nov 2023
