### ISSUE TITLE
[QA] RelevanceV2 finds 'dollar' where the word does not occur

### ISSUE THREAD

**Issue by jnweiger** [owncloud/search_elastic#329]
Seen with search-elastic-230+refactor-connector branch 20230714

* Prepare both connectors: `occ config:app:set search_elastic connectors_write --value "Legacy,RelevanceV2"`
* Enable `occ config:app:set search_elastic connectors_search --value Legacy`
* Add two PDF files that discuss world economics. The word `dollar` appears in these files.
* Search for `dollar` - results from these two files occur. OK.
![grafik](https://github.com/owncloud/search_elastic/assets/1108546/f77bcca7-9a31-4526-a1e3-cb15efe37569)
----
* Enable `occ config:app:set search_elastic connectors_search --value RelevanceV2`
* Search for `dollar` - results from many other files, even from JPEGs occur. BAD
![grafik](https://github.com/owncloud/search_elastic/assets/1108546/f9292819-9e74-4934-8391-9a0fba7c5785)

Is RelevanceV2 creating a match for the `$` sign?
(Or maybe this is just a duplicate of #331)

**Comment by jvillafanez** [comment]
Yes. The reason is the same as in #331

**Comment by jnweiger** [comment]
Yes. This is now fixed.
